openapi: 3.0.3
info:
  title: API de Usuários
  description: API para gerenciamento de usuários do sistema.
  version: 1.0.0

tags:
  - name: Usuarios
    description: Operações relacionadas a usuários.

paths:

  /usuarios/username:
    get:
      summary: Consultar por usuario
      operationId: consultarPorUsuario
      tags:
        - Usuarios
      parameters:
        - $ref: '#/components/parameters/ConsultaUsuario'
      responses:
        '200':
          description: Usuário encontrado com sucesso.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UsuarioResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalError'

  /usuarios:
    get:
      summary: Buscar e filtrar usuários (com paginação)
      operationId: buscarUsuariosPaginado
      tags:
        - Usuarios
      parameters:
        - $ref: '#/components/parameters/ConsultaUsuario'
        - $ref: '#/components/parameters/ConsultaUsuarioAtivo'
        - $ref: '#/components/parameters/Page'
        - $ref: '#/components/parameters/Size'
        - $ref: '#/components/parameters/Sort'
      responses:
        '200':
          description: Lista de usuários encontrada com sucesso.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BuscarUsuariosPaginado'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalError'

    post:
      summary: Criar novo usuário
      operationId: criarUsuario
      tags:
        - Usuarios
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UsuarioRequest'
      responses:
        '201':
          description: Usuário criado com sucesso.
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '500':
          $ref: '#/components/responses/InternalError'

  /usuarios/{id}:
    get:
      summary: Consultar usuário por ID (sem paginação)
      operationId: consultarUsuarioPorId
      tags:
        - Usuarios
      parameters:
        - $ref: '#/components/parameters/PathId'
      responses:
        '200':
          description: Usuário encontrado com sucesso.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UsuarioResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalError'

    put:
      summary: Atualizar usuário existente
      operationId: atualizarUsuario
      tags:
        - Usuarios
      parameters:
        - $ref: '#/components/parameters/PathId'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UsuarioRequest'
      responses:
        '204':
          description: Usuário atualizado com sucesso.
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalError'

    delete:
      summary: Excluir usuário
      operationId: excluirUsuario
      tags:
        - Usuarios
      parameters:
        - $ref: '#/components/parameters/PathId'
      responses:
        '204':
          description: Usuário excluído com sucesso.
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalError'


components:
  schemas:
    UsuarioRequest:
      type: object
      properties:
        usuario:
          type: string
          example: jdoe
        nome:
          type: string
          example: João da Silva
        password:
          type: string
          example: $enh@2025
        email:
          type: string
          example: joao.silva@email.com
        usuarioAtivo:
          type: boolean
          example: true

    UsuarioResponse:
      allOf:
        - $ref: '#/components/schemas/UsuarioRequest'
        - type: object
          properties:
            id:
              type: string
              example: 652ff3a9b1c2d40012ab45de
            password:
              type: string
              example: sdfsdfasdf45df4asd21sad5fas2d1fsdf54
            dataCriacao:
              type: string
              format: date-time
              example: 2025-10-11T10:15:30Z
            dataAlteracao:
              type: string
              format: date-time
              example: 2025-10-11T10:20:45Z

    BuscarUsuariosPaginado:
      type: object
      properties:
        content:
          type: array
          items:
            $ref: '#/components/schemas/UsuarioResponse'
        totalElements:
          type: integer
          example: 125
        totalPages:
          type: integer
          example: 13
        size:
          type: integer
          example: 10
        number:
          type: integer
          example: 0

    ApiError:
      type: object
      properties:
        status:
          type: integer
          example: 400
        error:
          type: string
          example: Bad Request
        message:
          type: string
          example: Parâmetros inválidos.
        path:
          type: string
          example: /usuarios
        timestamp:
          type: string
          format: date-time
          example: 2025-10-11T10:30:00Z

  parameters:
    ConsultaId:
      name: id
      in: query
      required: true
      schema:
        type: string
      description: ID do usuário (obrigatório para consultas sem paginação).

    ConsultaUsuario:
      name: usuario
      in: query
      required: false
      schema:
        type: string
      description: Username usuario.

    ConsultaUsuarioAtivo:
      name: usuarioAtivo
      in: query
      required: false
      schema:
        type: boolean
      description: Indica se o usuário está ativo.

    PathId:
      name: id
      in: path
      required: true
      schema:
        type: string
      description: ID do usuário (obrigatório para update e delete).

    Page:
      name: page
      in: query
      required: false
      schema:
        type: integer
        example: 0
      description: Número da página.

    Size:
      name: size
      in: query
      required: false
      schema:
        type: integer
        example: 10
      description: Quantidade de registros por página.

    Sort:
      name: sort
      in: query
      required: false
      schema:
        type: string
        example: nome,asc
      description: "Campo e direção de ordenação (ex: nome,asc ou id,desc)."

  responses:
    BadRequest:
      description: Requisição inválida.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ApiError'

    Unauthorized:
      description: Falha de autenticação.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ApiError'

    Forbidden:
      description: Acesso negado.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ApiError'

    NotFound:
      description: Recurso não encontrado.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ApiError'

    InternalError:
      description: Erro interno do servidor.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ApiError'